project:
  type: website
  output-dir: docs

website:
  title: "Michela Dumas"
  navbar:
    pinned: true
    left:
      - text: Projects 
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: "CV"
        href: cv/index.qmd
    right: 
      - icon: github
        href: https://github.com/micheladumas
      - icon: twitter
        href: https://x.com/michela_dumas
      - icon: linkedin
        href: https://www.linkedin.com/in/michela-dumas-100611227/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true